#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Venereissu_backend
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Venereissu")]
	public partial class VenereissutDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKohteet(Kohteet instance);
    partial void UpdateKohteet(Kohteet instance);
    partial void DeleteKohteet(Kohteet instance);
    partial void InsertKohteetReissut(KohteetReissut instance);
    partial void UpdateKohteetReissut(KohteetReissut instance);
    partial void DeleteKohteetReissut(KohteetReissut instance);
    partial void InsertReissut(Reissut instance);
    partial void UpdateReissut(Reissut instance);
    partial void DeleteReissut(Reissut instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    #endregion
		
		public VenereissutDataContext() : 
				base(global::Venereissu_backend.Properties.Settings.Default.VenereissuConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public VenereissutDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VenereissutDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VenereissutDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VenereissutDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Kohteet> Kohteets
		{
			get
			{
				return this.GetTable<Kohteet>();
			}
		}
		
		public System.Data.Linq.Table<KohteetReissut> KohteetReissuts
		{
			get
			{
				return this.GetTable<KohteetReissut>();
			}
		}
		
		public System.Data.Linq.Table<Reissut> Reissuts
		{
			get
			{
				return this.GetTable<Reissut>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kohteet")]
	public partial class Kohteet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Kohde_Id;
		
		private string _Nimi;
		
		private string _Koordinaatit;
		
		private string _KuvaBase64;
		
		private string _Kuvausteksti;
		
		private EntitySet<KohteetReissut> _KohteetReissuts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKohde_IdChanging(int value);
    partial void OnKohde_IdChanged();
    partial void OnNimiChanging(string value);
    partial void OnNimiChanged();
    partial void OnKoordinaatitChanging(string value);
    partial void OnKoordinaatitChanged();
    partial void OnKuvaBase64Changing(string value);
    partial void OnKuvaBase64Changed();
    partial void OnKuvaustekstiChanging(string value);
    partial void OnKuvaustekstiChanged();
    #endregion
		
		public Kohteet()
		{
			this._KohteetReissuts = new EntitySet<KohteetReissut>(new Action<KohteetReissut>(this.attach_KohteetReissuts), new Action<KohteetReissut>(this.detach_KohteetReissuts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kohde_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Kohde_Id
		{
			get
			{
				return this._Kohde_Id;
			}
			set
			{
				if ((this._Kohde_Id != value))
				{
					this.OnKohde_IdChanging(value);
					this.SendPropertyChanging();
					this._Kohde_Id = value;
					this.SendPropertyChanged("Kohde_Id");
					this.OnKohde_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nimi", DbType="NVarChar(50)")]
		public string Nimi
		{
			get
			{
				return this._Nimi;
			}
			set
			{
				if ((this._Nimi != value))
				{
					this.OnNimiChanging(value);
					this.SendPropertyChanging();
					this._Nimi = value;
					this.SendPropertyChanged("Nimi");
					this.OnNimiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Koordinaatit", DbType="NVarChar(50)")]
		public string Koordinaatit
		{
			get
			{
				return this._Koordinaatit;
			}
			set
			{
				if ((this._Koordinaatit != value))
				{
					this.OnKoordinaatitChanging(value);
					this.SendPropertyChanging();
					this._Koordinaatit = value;
					this.SendPropertyChanged("Koordinaatit");
					this.OnKoordinaatitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KuvaBase64", DbType="NVarChar(MAX)")]
		public string KuvaBase64
		{
			get
			{
				return this._KuvaBase64;
			}
			set
			{
				if ((this._KuvaBase64 != value))
				{
					this.OnKuvaBase64Changing(value);
					this.SendPropertyChanging();
					this._KuvaBase64 = value;
					this.SendPropertyChanged("KuvaBase64");
					this.OnKuvaBase64Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kuvausteksti", DbType="NVarChar(MAX)")]
		public string Kuvausteksti
		{
			get
			{
				return this._Kuvausteksti;
			}
			set
			{
				if ((this._Kuvausteksti != value))
				{
					this.OnKuvaustekstiChanging(value);
					this.SendPropertyChanging();
					this._Kuvausteksti = value;
					this.SendPropertyChanged("Kuvausteksti");
					this.OnKuvaustekstiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kohteet_KohteetReissut", Storage="_KohteetReissuts", ThisKey="Kohde_Id", OtherKey="Kohde_Id")]
		public EntitySet<KohteetReissut> KohteetReissuts
		{
			get
			{
				return this._KohteetReissuts;
			}
			set
			{
				this._KohteetReissuts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KohteetReissuts(KohteetReissut entity)
		{
			this.SendPropertyChanging();
			entity.Kohteet = this;
		}
		
		private void detach_KohteetReissuts(KohteetReissut entity)
		{
			this.SendPropertyChanging();
			entity.Kohteet = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KohteetReissut")]
	public partial class KohteetReissut : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KohdeReissu_Id;
		
		private int _Kohde_Id;
		
		private int _Reissu_Id;
		
		private string _KuvaBase64;
		
		private System.Nullable<System.DateTime> _Saapuminen;
		
		private System.Nullable<System.DateTime> _Lahteminen;
		
		private string _Tapahtumat;
		
		private EntityRef<Kohteet> _Kohteet;
		
		private EntityRef<Reissut> _Reissut;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKohdeReissu_IdChanging(int value);
    partial void OnKohdeReissu_IdChanged();
    partial void OnKohde_IdChanging(int value);
    partial void OnKohde_IdChanged();
    partial void OnReissu_IdChanging(int value);
    partial void OnReissu_IdChanged();
    partial void OnKuvaBase64Changing(string value);
    partial void OnKuvaBase64Changed();
    partial void OnSaapuminenChanging(System.Nullable<System.DateTime> value);
    partial void OnSaapuminenChanged();
    partial void OnLahteminenChanging(System.Nullable<System.DateTime> value);
    partial void OnLahteminenChanged();
    partial void OnTapahtumatChanging(string value);
    partial void OnTapahtumatChanged();
    #endregion
		
		public KohteetReissut()
		{
			this._Kohteet = default(EntityRef<Kohteet>);
			this._Reissut = default(EntityRef<Reissut>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KohdeReissu_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int KohdeReissu_Id
		{
			get
			{
				return this._KohdeReissu_Id;
			}
			set
			{
				if ((this._KohdeReissu_Id != value))
				{
					this.OnKohdeReissu_IdChanging(value);
					this.SendPropertyChanging();
					this._KohdeReissu_Id = value;
					this.SendPropertyChanged("KohdeReissu_Id");
					this.OnKohdeReissu_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kohde_Id", DbType="Int NOT NULL")]
		public int Kohde_Id
		{
			get
			{
				return this._Kohde_Id;
			}
			set
			{
				if ((this._Kohde_Id != value))
				{
					if (this._Kohteet.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKohde_IdChanging(value);
					this.SendPropertyChanging();
					this._Kohde_Id = value;
					this.SendPropertyChanged("Kohde_Id");
					this.OnKohde_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reissu_Id", DbType="Int NOT NULL")]
		public int Reissu_Id
		{
			get
			{
				return this._Reissu_Id;
			}
			set
			{
				if ((this._Reissu_Id != value))
				{
					if (this._Reissut.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnReissu_IdChanging(value);
					this.SendPropertyChanging();
					this._Reissu_Id = value;
					this.SendPropertyChanged("Reissu_Id");
					this.OnReissu_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KuvaBase64", DbType="NVarChar(MAX)")]
		public string KuvaBase64
		{
			get
			{
				return this._KuvaBase64;
			}
			set
			{
				if ((this._KuvaBase64 != value))
				{
					this.OnKuvaBase64Changing(value);
					this.SendPropertyChanging();
					this._KuvaBase64 = value;
					this.SendPropertyChanged("KuvaBase64");
					this.OnKuvaBase64Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Saapuminen", DbType="DateTime")]
		public System.Nullable<System.DateTime> Saapuminen
		{
			get
			{
				return this._Saapuminen;
			}
			set
			{
				if ((this._Saapuminen != value))
				{
					this.OnSaapuminenChanging(value);
					this.SendPropertyChanging();
					this._Saapuminen = value;
					this.SendPropertyChanged("Saapuminen");
					this.OnSaapuminenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lahteminen", DbType="DateTime")]
		public System.Nullable<System.DateTime> Lahteminen
		{
			get
			{
				return this._Lahteminen;
			}
			set
			{
				if ((this._Lahteminen != value))
				{
					this.OnLahteminenChanging(value);
					this.SendPropertyChanging();
					this._Lahteminen = value;
					this.SendPropertyChanged("Lahteminen");
					this.OnLahteminenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tapahtumat", DbType="NVarChar(MAX)")]
		public string Tapahtumat
		{
			get
			{
				return this._Tapahtumat;
			}
			set
			{
				if ((this._Tapahtumat != value))
				{
					this.OnTapahtumatChanging(value);
					this.SendPropertyChanging();
					this._Tapahtumat = value;
					this.SendPropertyChanged("Tapahtumat");
					this.OnTapahtumatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kohteet_KohteetReissut", Storage="_Kohteet", ThisKey="Kohde_Id", OtherKey="Kohde_Id", IsForeignKey=true)]
		public Kohteet Kohteet
		{
			get
			{
				return this._Kohteet.Entity;
			}
			set
			{
				Kohteet previousValue = this._Kohteet.Entity;
				if (((previousValue != value) 
							|| (this._Kohteet.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kohteet.Entity = null;
						previousValue.KohteetReissuts.Remove(this);
					}
					this._Kohteet.Entity = value;
					if ((value != null))
					{
						value.KohteetReissuts.Add(this);
						this._Kohde_Id = value.Kohde_Id;
					}
					else
					{
						this._Kohde_Id = default(int);
					}
					this.SendPropertyChanged("Kohteet");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Reissut_KohteetReissut", Storage="_Reissut", ThisKey="Reissu_Id", OtherKey="Reissu_Id", IsForeignKey=true)]
		public Reissut Reissut
		{
			get
			{
				return this._Reissut.Entity;
			}
			set
			{
				Reissut previousValue = this._Reissut.Entity;
				if (((previousValue != value) 
							|| (this._Reissut.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Reissut.Entity = null;
						previousValue.KohteetReissuts.Remove(this);
					}
					this._Reissut.Entity = value;
					if ((value != null))
					{
						value.KohteetReissuts.Add(this);
						this._Reissu_Id = value.Reissu_Id;
					}
					else
					{
						this._Reissu_Id = default(int);
					}
					this.SendPropertyChanged("Reissut");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Reissut")]
	public partial class Reissut : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Reissu_Id;
		
		private string _Nimi;
		
		private System.Nullable<System.DateTime> _Alkoi;
		
		private System.Nullable<System.DateTime> _Paattyi;
		
		private string _Kuvausteksti;
		
		private string _UserName;
		
		private EntitySet<KohteetReissut> _KohteetReissuts;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnReissu_IdChanging(int value);
    partial void OnReissu_IdChanged();
    partial void OnNimiChanging(string value);
    partial void OnNimiChanged();
    partial void OnAlkoiChanging(System.Nullable<System.DateTime> value);
    partial void OnAlkoiChanged();
    partial void OnPaattyiChanging(System.Nullable<System.DateTime> value);
    partial void OnPaattyiChanged();
    partial void OnKuvaustekstiChanging(string value);
    partial void OnKuvaustekstiChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    #endregion
		
		public Reissut()
		{
			this._KohteetReissuts = new EntitySet<KohteetReissut>(new Action<KohteetReissut>(this.attach_KohteetReissuts), new Action<KohteetReissut>(this.detach_KohteetReissuts));
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reissu_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Reissu_Id
		{
			get
			{
				return this._Reissu_Id;
			}
			set
			{
				if ((this._Reissu_Id != value))
				{
					this.OnReissu_IdChanging(value);
					this.SendPropertyChanging();
					this._Reissu_Id = value;
					this.SendPropertyChanged("Reissu_Id");
					this.OnReissu_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nimi", DbType="NVarChar(50)")]
		public string Nimi
		{
			get
			{
				return this._Nimi;
			}
			set
			{
				if ((this._Nimi != value))
				{
					this.OnNimiChanging(value);
					this.SendPropertyChanging();
					this._Nimi = value;
					this.SendPropertyChanged("Nimi");
					this.OnNimiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alkoi", DbType="DateTime")]
		public System.Nullable<System.DateTime> Alkoi
		{
			get
			{
				return this._Alkoi;
			}
			set
			{
				if ((this._Alkoi != value))
				{
					this.OnAlkoiChanging(value);
					this.SendPropertyChanging();
					this._Alkoi = value;
					this.SendPropertyChanged("Alkoi");
					this.OnAlkoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paattyi", DbType="DateTime")]
		public System.Nullable<System.DateTime> Paattyi
		{
			get
			{
				return this._Paattyi;
			}
			set
			{
				if ((this._Paattyi != value))
				{
					this.OnPaattyiChanging(value);
					this.SendPropertyChanging();
					this._Paattyi = value;
					this.SendPropertyChanged("Paattyi");
					this.OnPaattyiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kuvausteksti", DbType="NVarChar(MAX)")]
		public string Kuvausteksti
		{
			get
			{
				return this._Kuvausteksti;
			}
			set
			{
				if ((this._Kuvausteksti != value))
				{
					this.OnKuvaustekstiChanging(value);
					this.SendPropertyChanging();
					this._Kuvausteksti = value;
					this.SendPropertyChanged("Kuvausteksti");
					this.OnKuvaustekstiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Reissut_KohteetReissut", Storage="_KohteetReissuts", ThisKey="Reissu_Id", OtherKey="Reissu_Id")]
		public EntitySet<KohteetReissut> KohteetReissuts
		{
			get
			{
				return this._KohteetReissuts;
			}
			set
			{
				this._KohteetReissuts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Reissut", Storage="_User", ThisKey="UserName", OtherKey="UserName", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.Reissuts.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.Reissuts.Add(this);
						this._UserName = value.UserName;
					}
					else
					{
						this._UserName = default(string);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KohteetReissuts(KohteetReissut entity)
		{
			this.SendPropertyChanging();
			entity.Reissut = this;
		}
		
		private void detach_KohteetReissuts(KohteetReissut entity)
		{
			this.SendPropertyChanging();
			entity.Reissut = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserName;
		
		private string _Password;
		
		private string _SessionId;
		
		private System.Nullable<System.DateTime> _TimeStamp;
		
		private EntitySet<Reissut> _Reissuts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnSessionIdChanging(string value);
    partial void OnSessionIdChanged();
    partial void OnTimeStampChanging(System.Nullable<System.DateTime> value);
    partial void OnTimeStampChanged();
    #endregion
		
		public User()
		{
			this._Reissuts = new EntitySet<Reissut>(new Action<Reissut>(this.attach_Reissuts), new Action<Reissut>(this.detach_Reissuts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SessionId", DbType="VarChar(50)")]
		public string SessionId
		{
			get
			{
				return this._SessionId;
			}
			set
			{
				if ((this._SessionId != value))
				{
					this.OnSessionIdChanging(value);
					this.SendPropertyChanging();
					this._SessionId = value;
					this.SendPropertyChanged("SessionId");
					this.OnSessionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeStamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> TimeStamp
		{
			get
			{
				return this._TimeStamp;
			}
			set
			{
				if ((this._TimeStamp != value))
				{
					this.OnTimeStampChanging(value);
					this.SendPropertyChanging();
					this._TimeStamp = value;
					this.SendPropertyChanged("TimeStamp");
					this.OnTimeStampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Reissut", Storage="_Reissuts", ThisKey="UserName", OtherKey="UserName")]
		public EntitySet<Reissut> Reissuts
		{
			get
			{
				return this._Reissuts;
			}
			set
			{
				this._Reissuts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Reissuts(Reissut entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_Reissuts(Reissut entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
	}
}
#pragma warning restore 1591
